import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import domtoimage from "dom-to-image";

export const generateReport = async ({
  form,
  result,
  pieRef,
  trendRef,
  mineRef,
}) => {
  const doc = new jsPDF("p", "mm", "a4");

  /* ================= TITLE ================= */
  doc.setFontSize(20);
  doc.setTextColor(220, 38, 38);
  doc.text("CoalCarbon Insight", 14, 20);

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Carbon Footprint Assessment Report", 14, 30);
  doc.line(14, 33, 196, 33);

  /* ================= INPUT TABLE ================= */
  autoTable(doc, {
    startY: 45,
    head: [["Parameter", "Value"]],
    body: [
      ["Diesel Used (Litres)", form.dieselLitres],
      ["Electricity Used (kWh)", form.electricityKwh],
      ["Explosives Used (kg)", form.explosivesKg],
      ["Methane Emitted (tons)", form.methaneTons],
    ],
  });

  /* ================= BREAKDOWN TABLE ================= */
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Source", "Emissions (kg CO₂e)"]],
    body: [
      ["Diesel", result.breakdown.diesel.toFixed(2)],
      ["Electricity", result.breakdown.electricity.toFixed(2)],
      ["Explosives", result.breakdown.explosives.toFixed(2)],
      ["Methane", result.breakdown.methane.toFixed(2)],
    ],
  });

  /* ================= TOTAL ================= */
  doc.setFontSize(14);
  doc.setTextColor(0, 128, 0);
  doc.text(
    `Total CO₂ Emissions: ${result.totalCO2e} kg`,
    14,
    doc.lastAutoTable.finalY + 15
  );

  /* ================= CHART HELPER ================= */
  const addChartToPDF = async (ref, title) => {
    if (!ref?.current) return;

    const dataUrl = await domtoimage.toPng(ref.current, {
      bgcolor: "#ffffff",
      quality: 1,
      scale: 2,
    });

    doc.addPage();
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(title, 14, 20);
    doc.addImage(dataUrl, "PNG", 10, 30, 190, 120);
  };

  /* ================= CHART PAGES ================= */
  await addChartToPDF(pieRef, "Emission Breakdown");
  await addChartToPDF(trendRef, "Multi-Year Emission Trend");
  await addChartToPDF(mineRef, "Mine-wise Emission Comparison");

  /* ================= FOOTER ================= */
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by CoalCarbon Insight | Sustainability Analytics Tool",
    14,
    285
  );

  doc.save("CoalCarbon_Report.pdf");
};
